"""Collect results/*.json into REPORT_results.md + plots (results/plots/*.png)."""
import csv
import glob
import json
import os

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt  # noqa: E402

MAIN = ["run1_baseline", "run2_rev_same", "run3_rev_max", "run1b_baseline_max", "run3b_rev_max_fp32stream",
        "colab_run3_rev_max_fp64"]
LABEL = {"run1_baseline": "Run 1 baseline", "run2_rev_same": "Run 2 reversible, same batch",
         "run3_rev_max": "Run 3 reversible, max batch", "run1b_baseline_max": "Run 1b baseline, max batch",
         "colab_run3_rev_max_fp64": "Colab Run 3 reference (fp64 stream)",
         "run3b_rev_max_fp32stream": "Run 3b reversible, max batch, fp32 stream"}


def load(pattern):
    return {os.path.basename(p)[:-5]: json.load(open(p)) for p in sorted(glob.glob(pattern))}


def fmt(v, f="{:.3f}"):
    return "—" if v is None else f.format(v)


def row(name, r):
    return (f"| {name} | {r['trunk']} | {r['h'] if 'rev' in r['trunk'] or 'mid' in r['trunk'] else '—'} "
            f"| {r.get('stream', 'fp32')} | {r['batch']} | {r['steps']} | {fmt(r['final_train_loss'])} "
            f"| {fmt(r['val_loss'])} | {r['tokens_per_s']:,.0f} | {fmt(r['tokens_per_s_steady'], '{:,.0f}')} "
            f"| {r['peak_mem_gib']:.2f} | {fmt(r['recon_error'], '{:.1e}')} | {r.get('gpu', '').replace('NVIDIA ', '')} |")


HDR = ("| run | trunk | h | stream | batch | steps | final train loss | val loss | tokens/s | tokens/s (steady) "
       "| peak mem (GiB) | recon err |\n|---|---|---|---|---|---|---|---|---|---|---|---|")


def curves(runs, folder, path, title):
    plt.figure(figsize=(7, 4))
    for name in runs:
        f = os.path.join(folder, f"{name}.csv")
        if not os.path.exists(f):
            continue
        rows = list(csv.DictReader(open(f)))
        plt.plot([int(r["tokens"]) / 1e6 for r in rows], [float(r["loss"]) for r in rows],
                 label=LABEL.get(name, name), lw=1)
    plt.xlabel("tokens (M)")
    plt.ylabel("train loss")
    plt.ylim(1.5, 6.0)
    plt.title(title)
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(path, dpi=120)
    plt.close()


def bars(res, path):
    gpu = res.get("run1_baseline", {}).get("gpu")
    names = [n for n in MAIN if n in res and res[n].get("gpu") == gpu]  # tokens/s only comparable on one GPU
    fig, ax = plt.subplots(1, 2, figsize=(10, 3.8))
    lbl = [f"{LABEL[n].split(' ', 2)[1]}\n{res[n]['trunk']}\nB={res[n]['batch']}" for n in names]
    ax[0].bar(lbl, [res[n]["tokens_per_s_steady"] / 1e3 for n in names], color="#4C78A8")
    ax[0].set_title("throughput (k tokens/s, steady)")
    ax[1].bar(lbl, [res[n]["peak_mem_gib"] for n in names], color="#F58518")
    ax[1].set_title("peak memory allocated (GiB)")
    for a in ax:
        a.tick_params(axis="x", labelsize=8)
        a.grid(axis="y", alpha=0.3)
    plt.tight_layout()
    plt.savefig(path, dpi=120)
    plt.close()


def main():
    os.makedirs("results/plots", exist_ok=True)
    out = ["# Results (auto-generated by make_report.py)\n"]
    screen = load("results/screen/*.json")
    if screen:
        out += ["## Integrator screening (5M tokens, batch 32)\n", HDR]
        out += [row(n, r) for n, r in screen.items()]
        curves(list(screen), "results/screen", "results/plots/screen_loss.png", "Integrator screening")
        out += ["\n![screening](results/plots/screen_loss.png)\n"]

    res = {n: r for n, r in load("results/*.json").items() if n in MAIN}
    if res:
        out += ["## Main runs (50M tokens)\n", HDR]
        out += [row(LABEL[n], res[n]) for n in MAIN if n in res]
        curves([n for n in MAIN if n in res], "results", "results/plots/main_loss.png", "Main runs")
        bars(res, "results/plots/main_bars.png")
        out += ["\n![loss](results/plots/main_loss.png)\n", "![bars](results/plots/main_bars.png)\n"]
        if all(k in res for k in MAIN[:3]):
            b, s, m = res["run1_baseline"], res["run2_rev_same"], res["run3_rev_max"]
            k = "tokens_per_s_steady"
            out += ["## Headline numbers\n",
                    f"- Peak memory at equal batch: {b['peak_mem_gib']:.2f} → {s['peak_mem_gib']:.2f} GiB "
                    f"(**{100 * (1 - s['peak_mem_gib'] / b['peak_mem_gib']):.0f}% lower**)",
                    f"- Throughput at equal batch: {b[k]:,.0f} → {s[k]:,.0f} tok/s "
                    f"(**{100 * (1 - s[k] / b[k]):.0f}% slower**)",
                    f"- Reversible at max batch {m['batch']}: {m[k]:,.0f} tok/s = "
                    f"**{100 * m[k] / b[k]:.0f}% of baseline** throughput, peak {m['peak_mem_gib']:.2f} GiB",
                    f"- Val loss: baseline {b['val_loss']:.3f}, rev same-batch {s['val_loss']:.3f}, "
                    f"rev max-batch {m['val_loss']:.3f}"]
            if "run1b_baseline_max" in res:
                bm = res["run1b_baseline_max"]
                out += [f"- Baseline at its own max batch {bm['batch']}: {bm[k]:,.0f} tok/s, "
                        f"val {bm['val_loss']:.3f}, peak {bm['peak_mem_gib']:.2f} GiB"]
    mb = load("results/maxbatch_*.json")
    if mb:
        out += ["\n## Max batch probes (13.5 GiB budget)\n"]
        out += [f"- {r['trunk']} (stream {r['stream']}): **{r['max_batch']}**" for r in mb.values()]
    open("REPORT_results.md", "w", encoding="utf-8").write("\n".join(out) + "\n")
    print("wrote REPORT_results.md")


if __name__ == "__main__":
    main()
